package com.mix.springsecurity.authorization;

import org.springframework.security.web.authentication.AbstractAuthenticationTargetUrlRequestHandler;

public class SecAuthenticationTargetUrlRequestHandler extends AbstractAuthenticationTargetUrlRequestHandler{

}
